name: Weekly Zip Project

on:
  schedule:
    - cron: '0 0 * * 0' # This cron job runs at midnight on Sundays
  workflow_dispatch: # Allows manual triggering

jobs:
  zip:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set WEEK variable
        run: echo "WEEK=$(date +%U)" >> $GITHUB_ENV # Export the week number as an environment variable

      - name: Create zip file
        run: |
          ZIP_FILE="project-week-${WEEK}.zip"
          zip -r $ZIP_FILE . # Create a zip of the entire project directory

      - name: Upload zip file
        uses: actions/upload-artifact@v3
        with:
          name: project-week-${{ env.WEEK }}.zip # Use the environment variable
          path: project-week-${{ env.WEEK }}.zip # Use the environment variable for the file path
